Food/urls.py
from django.urls import path
from . import views


# for Namespacing
app_name = 'food'


urlpatterns = [
    # food/
    path('', views.IndexClassView.as_view(), name='index'),

    # food/1/
    path('<int:pk>/', views.FoodDetail.as_view(), name='Detail'),
    path('item/', views.item, name='item'),

    # Add a Form
    path('add', views.CreateItem.as_view(), name='create_item'),

    # Update a Form
    path('update/<int:id>/', views.update_item, name='update_item'),

    # Delete a item
    path('delete/<int:id>/', views.delete_item, name='delete_item'),

]

mysite/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include
from Users import views as user_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('Food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profilepage, name='profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class Item(models.Model):
    """ Model for Food Items """

    def __str__(self) -> str:
        return str(self.item_name)

    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField(default=0)
    item_image = models.CharField(
        max_length=500,
        default='https://cdn.pixabay.com/photo/2017/02/16/02/54/coming-soon-2070393_1280.jpg')

    def get_absolute_url(self):
        """ Redirect to the detail page """
        return reverse('food:Detail', kwargs={'pk': self.pk})

Users/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Profile(models.Model):
    """Model for user profile."""

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(
        default='default.jpg', upload_to='profile_pics')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

Food/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

Users/forms.py
""" Forms for the Users app."""

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    """ Form for registering a new user."""
    email = forms.EmailField()

    class Meta:
        """ Meta class for the form."""
        model = User
        fields = ['username', 'email', 'password1', 'password2']

Food/views.py
""" This file is used to create the views for the food app. """

from django.views.generic import ListView, DetailView, CreateView
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import ItemForm
from .models import Item


# Create your views here.


# def index(request): # This is a function based view

#     item_list = Item.objects.all()
#     context = {
#         'item_list': item_list,
#     }
#     return render(request, 'food/index.html', context)


class IndexClassView(ListView):
    """ This class is used to display the items.  This is a class based view. """
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'


def item(request):
    """ This function is used to display the items. """

    return HttpResponse("<h1>Hello, world. You're at the polls item.</h1>")


# def detail(request, item_id):
#     """ This function is used to display the details of the item. """

#     item = Item.objects.get(pk=item_id)
#     context = {
#         'item': item,
#     }

#     return render(request, 'food/detail.html', context)


class FoodDetail(DetailView):
    """ This class is used to display the details of the item. """

    model = Item
    template_name = 'food/detail.html'


# def create_item(request):
#     """ This function is used to create the item. """

#     form = ItemForm(request.POST or None)

#     if form.is_valid():
#         form.save()
#         return redirect('food:index')

#     context = {
#         'form': form,
#     }

#     return render(request, 'food/item-form.html', context)

class CreateItem(CreateView):
    """ This class is used to create the item. """

    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item-form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)


def update_item(request, id):
    """ This function is used to update the item. """

    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    context = {
        'form': form,
        'item': item,
    }

    return render(request, 'food/item-form.html', context)


def delete_item(request, id):
    """ This function is used to delete the item. """

    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')

    context = {
        'item': item,
    }

    return render(request, 'food/delete-item.html', context)

Users/views.py
""" Views for the Users app. """

from django.shortcuts import render, redirect
from django.contrib import messages
from . forms import RegisterForm
from django.contrib.auth.decorators import login_required

# Create register view


def register(request):
    """Register a new user."""

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(
                request, f'Welcome {username}! Your account has been created.')
            return redirect('login')
    else:
        form = RegisterForm()

    context = {'form': form}
    return render(request, 'users/register.html', context)


@login_required
def profilepage(request):
    """ Profile page for the user."""

    return render(request, 'users/profile.html')

Food/templates/food/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food Menu</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
</head>

<body>

    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Food Menu</a>

        <div class="navbar">
            <a class="nav-link nav-item" href="{% url 'food:create_item' %}">Add Item</a>
            <a class="nav-link nav-item" href="#">Edit Item</a>
            <a class="nav-link nav-item" href="#">View Item</a>

            {% if user.is_authenticated %}
            <a class="nav-link nav-item" href="{% url 'profile' %}">Profile</a>
            <form action="{% url 'logout' %}" method="post" style="display:inline;">
                {% csrf_token %}
                <button type="submit" class="nav-link nav-item btn btn-link">Logout</button>
            </form>

            {% else %}
            <a class="nav-link nav-item" href="{% url 'login' %}">Login</a>
            <a class="nav-link nav-item" href="{% url 'register' %}">Register</a>
            {% endif %}

        </div>
    </nav>

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}

    {% block body %}
    {% endblock %}

</body>

</html>

Food/templates/food/delete-item.html
{% extends 'food/base.html' %}
{% block body %}


<form method="post">

    {% csrf_token %}
    <h3>Are you sure you want to delete "{{ item.item_name }}"?</h3>
    <button type="submit"> Confirm </button>



</form>




{% endblock %}

Food/templates/food/detail.html
{% extends 'food/base.html' %}


{% block body %}

<div class="container mt-5 mx-10">

    <div class="row">
        <div class="col-md-6">
            <img class="card" height="300px" src="{{item.item_image}}" />

        </div>

        <div class="col-md-6">

            <h3>{{object.item_name}}</h3>
            <h4>{{object.item_desc}}</h4>
            <h5>${{object.item_price}}</h5>

            <a href="{% url 'food:delete_item' item.id %}">Delete</a>

        </div>


    </div>

    {% endblock %}

Food/templates/food/index.html
{% extends 'food/base.html' %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>

    {% block body %}

    {% for item in item_list %}

    <div class=" row mt-5 mx-10 ">
        <div class="col-md-3 offset-md-2">
            <img class="card" height="150px" src="{{item.item_image}}" />

        </div>

        <div class="col-md-4 ">

            <h3>{{item.item_name}}</h3>
            <h4>{{item.item_desc}}</h4>
            <h5>${{item.item_price}}</h5>

        </div>

        <div class="col-md-2">

            <a href="{% url 'food:Detail' item.id %}" class="btn btn-success">Details</a>

        </div>






    </div>




    {% endfor %}

    {% endblock %}
</body>

</html>

Food/templates/food/item-form.html
{% extends 'Food/base.html' %}

{% block body %}

<div class="container mt-5">

    <div class="row">

        <div class="col-md-4 offset-md-4">

            <div class="card">

                <div class="card-header bg-primary text-white">

                    <div class="card-title text-center">
                        Add Item
                    </div>

                </div>

                <div class="card-body">

                    <form method="post">

                        {% csrf_token %}
                        {{ form}}

                        <div class="text-center">
                            <button class="btn-primary" type="submit">Add Item</button>
                        </div>
                    </form>

                </div>

            </div>

        </div>


    </div>

</div>

{% endblock %}

Users/templates/users/login.html
{% extends 'Food/base.html' %}

{% block body %}


<div class="container mt-5">

    <div class="row">

        <div class="col-md-4 offset-md-4">

            <div class="card">

                <div class="card-header bg-primary text-white">

                    <div class="card-title text-center">
                        Login
                    </div>

                </div>

                <div class="card-body">

                    <form method="post">

                        {% csrf_token %}

                        {% for field in form %}

                        <div class="form-group">

                            {{ field.name }}
                            {{ field }}
                        </div>

                        {% endfor %}
                        <div class="text-center">
                            <button class="btn-primary " type="submit">Login</button>
                        </div>

                    </form>


                </div>

            </div>

        </div>


    </div>

</div>

{% endblock %}

Users/templates/users/logout.html
{% extends 'Food/base.html' %}

{% block body %}

<div class="container mt-5 ">

    <h2 class="text-center">You have been logged out.</h2>
    <br>

    <div class="text-center">


        <a href="{% url 'login' %}" class="btn btn-primary mt-5">Login again</a>
        <br>
        <a href="{% url 'food:index' %}" class="btn btn-primary mt-2">Home</a>
    </div>

</div>

{% endblock %}

Users/templates/users/profile.html
{% extends 'Food/base.html' %}

{% block body %}

<div class="container mt-5 ">
    <h3>
        {{user.username}}
    </h3><br>

    <img src="{{user.profile.image.url}}" width="200" height="200"><br><br>

</div>

{% endblock %}

Users/templates/users/register.html
{% extends 'Food/base.html' %}

{% block body %}

<div class="container mt-5">

    <div class="row">

        <div class="col-md-4 offset-md-4">

            <div class="card">

                <div class="card-header bg-primary text-white">

                    <div class="card-title text-center">
                        Register
                    </div>

                </div>

                <div class="card-body">

                    <form method="post">

                        {% csrf_token %}

                        {% for field in form %}
                        <div class="form-group">
                            {{ field.name }}
                            <br>
                            {{ field }}
                        </div>

                        {% endfor %}
                        <div class="text-center">
                            <button class="btn-primary" type="submit">Sign Up</button>
                        </div>
                    </form>

                </div>

            </div>

        </div>


    </div>

</div>

{% endblock %}